# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmap.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MindMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='描述')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d/', verbose_name='图片')),
                ('mindmap', models.FileField(blank=True, null=True, upload_to='file/%Y/%m/%d/', verbose_name='思维导图文件')),
                ('share', models.URLField(blank=True, max_length=300, null=True, verbose_name='分享地址')),
                ('vote', models.IntegerField(default=0, verbose_name='投票')),
                ('visit', models.IntegerField(default=0, verbose_name='浏览')),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='mindmap.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('count', models.IntegerField(default=0, verbose_name='属于该标签记录数量')),
            ],
        ),
        migrations.AddField(
            model_name='mindmap',
            name='tags',
            field=models.ManyToManyField(to='mindmap.Tag'),
        ),
    ]
