# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0002_auto_20170728_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='mindmap.Category'),
        ),
    ]
