# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0004_auto_20170728_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='mindmap.Category'),
        ),
    ]
