# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0007_auto_20170728_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='mindmap',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='mindmap',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
