# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 02:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mindmap', '0009_mindmap_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='MindMapVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmap.MindMap')),
            ],
        ),
    ]
