# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0012_article_feedbackmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=10000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='feedbackmessage',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='内容'),
        ),
    ]
